#!/usr/bin/env python
from cement.core.foundation import CementApp
from controllers import base, setup, install, package

class AppImager(CementApp):
    class Meta:
        label = 'appimager'
        base_controller = 'base'
        handlers = [base.BaseController, setup.SetupController, install.InstallController, package.PackageController]

with AppImager() as app:
    app.run()
