#!/usr/bin/env python
from cement.core.foundation import CementApp
from controllers import base, install

class AppImager(CementApp):
    class Meta:
        label = 'appimager'
        base_controller = 'base'
        handlers = [base.BaseController, install.InstallController]

with AppImager() as app:
    app.run()
